name: Build

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4.1.5
    - name: Build our Project
      run: bash compile.sh

    - uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
      with:
          # The arguments for the `git add` command (see the paragraph below for more info)
          # Default: '.'
          add: '.'
  
          # The name of the user that will be displayed as the author of the commit.
          # Default: depends on the default_author input
          author_name: Silas Wrinker
  
          # The email of the user that will be displayed as the author of the commit.
          # Default: depends on the default_author input
          author_email: alcosojr79@gmail.com
  
          # Additional arguments for the git commit command. The --message argument is already set by the message input.
          # Default: ''
          commit: ''
  
          cwd: .
          
          # The message for the commit.
          # Default: 'Commit from GitHub Actions (name of the workflow)'
          message: 'Built project'
