name: C Project Build

on:
  workflow_dispatch:

jobs:
  build_c:
    name: build c project
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Build Our Project
      run: |
        gcc crate/main.c -o crate/crate.out

    - name: Commit Project
      uses: EndBug/add-and-commit@v9.1.4
      with:
        author_name: Silas Wrinker
        author_email: alcosojr79@gmail.com
        message: Built project
